# ape-config.yaml
name: ape-demo

default_ecosystem: ethereum

ethereum:
  default_network: local_moonbeam

  local_moonbeam:
    default_transaction_type: 0
    gas_limit: "auto"
    block_time: 6
    transaction_acceptance_timeout: 60
    max_receipt_retries: 10

networks:
  custom:
    - name: local_moonbeam
      chain_id: 1281                    
      ecosystem: ethereum
      base_ecosystem_plugin: ethereum
      default_provider: node

node:
  ethereum:
    local_moonbeam:
      uri: http://127.0.0.1:9944